CREATE NONCLUSTERED INDEX IX_HoSoKham_MaBN
ON HoSoKham(MaBN);
GO

CREATE NONCLUSTERED INDEX IX_HoSoKham_MaBS
ON HoSoKham(MaBS);
GO

CREATE NONCLUSTERED INDEX IX_HoSoKham_NgayKham
ON HoSoKham(NgayKham);
GO
