:r .\0_Database\CreateDatabase.sql
:r .\0_Database\UseDatabase.sql
:r .\1_Tables\Khoa.sql
:r .\1_Tables\Benh.sql
:r .\1_Tables\DichVu.sql
:r .\1_Tables\PhongKham.sql
:r .\1_Tables\Thuoc.sql
:r .\1_Tables\BacSi.sql
:r .\1_Tables\BenhNhan.sql
:r .\1_Tables\LichKham.sql
:r .\1_Tables\HoSoKham.sql
:r .\1_Tables\DonThuoc.sql
:r .\1_Tables\ChiTietDonThuoc.sql
:r .\1_Tables\ChiTietDichVu.sql
:r .\1_Tables\HoaDon.sql
:r .\1_Tables\ThanhToan.sql
:r .\2_Functions\fn_TinhTongChiPhiHoSo.sql
:r .\2_Functions\fn_TinhTongDichVuTraBenhVien.sql
:r .\2_Functions\fn_TinhTongDonThuocTraNhaThuoc.sql
:r .\2_Functions\fn_TinhTongDichVu.sql
:r .\2_Functions\fn_TinhTongDonThuoc.sql
:r .\3_Procedures\sp_ThemBenhNhan.sql
:r .\3_Procedures\sp_SuaBenhNhan.sql
:r .\3_Procedures\sp_XoaBenhNhan.sql
:r .\3_Procedures\sp_ThemBacSi.sql
:r .\3_Procedures\sp_SuaBacSi.sql
:r .\3_Procedures\sp_XoaBacSi.sql
:r .\3_Procedures\sp_ThemThuoc.sql
:r .\3_Procedures\sp_SuaThuoc.sql
:r .\3_Procedures\sp_XoaThuoc.sql
:r .\3_Procedures\sp_DatLichKham.sql
:r .\3_Procedures\sp_CapNhatTrangThaiLichKham.sql
:r .\3_Procedures\sp_ThemDonThuoc.sql
:r .\3_Procedures\sp_SuaDonThuoc.sql
:r .\3_Procedures\sp_XoaDonThuoc.sql
:r .\3_Procedures\sp_ThemChiTietDonThuoc.sql
:r .\3_Procedures\sp_ThemChiTietDichVu.sql
:r .\3_Procedures\sp_TaoHoaDonDayDu.sql
:r .\3_Procedures\sp_ThanhToanHoaDon.sql
:r .\3_Procedures\sp_ThongKeDoanhThuTongHop.sql
:r .\3_Procedures\sp_ThongKeThuocBanRa.sql
:r .\3_Procedures\sp_ThongKeLuotKhamThang.sql
:r .\3_Procedures\sp_ThongKeDoanhThuThang.sql
:r .\3_Procedures\sp_ThongKeBenhPhoBien.sql
:r .\4_Triggers\trg_KiemTraTrungLichKham.sql
:r .\4_Triggers\trg_CapNhatHoaDonKhiDichVuThayDoi.sql
:r .\4_Triggers\trg_CapNhatHoaDonKhiDonThuocThayDoi.sql
:r .\4_Triggers\trg_CapNhatTongTienDonThuoc.sql
:r .\4_Triggers\trg_CapNhatTienBNPhaiTra.sql
:r .\4_Triggers\trg_PhucHoiTonKhoSauXoa.sql
:r .\4_Triggers\trg_GiamTonKhoSauBan.sql
:r .\4_Triggers\trg_KiemTraXoaBenhNha.sql
:r .\4_Triggers\trg_KiemTraXoaBacSi.sql
:r .\5_Views\v_DoanhThuTheoThang.sql
:r .\5_Views\v_HoaDonChiTiet.sql
:r .\5_Views\v_LichSuKhamBenhNhan.sql
:r .\5_Views\v_DonThuocBenhNhan.sql
:r .\6_Data\Khoa.sql
:r .\6_Data\Benh.sql
:r .\6_Data\DichVu.sql
:r .\6_Data\PhongKham.sql
:r .\6_Data\Thuoc.sql
:r .\6_Data\BacSi.sql
:r .\6_Data\BenhNhan.sql
:r .\6_Data\LichKham.sql
:r .\6_Data\HoSoKham.sql
:r .\6_Data\DonThuoc.sql
:r .\6_Data\ChiTietDonThuoc.sql
:r .\6_Data\ChiTietDichVu.sql
:r .\6_Data\HoaDon.sql
:r .\6_Data\ThanhToan.sql
:r .\7_Indexes\HoSoKham.sql
:r .\7_Indexes\DonThuoc.sql
:r .\7_Indexes\HoaDon.sql
:r .\7_Indexes\LichKham.sql
