CREATE TABLE BacSi (
    MaBS INT PRIMARY KEY IDENTITY(1,1),
    HoTen NVARCHAR(100) NOT NULL,
    GioiTinh NVARCHAR(10) NULL,
    NgaySinh DATE NULL,
    SDT NVARCHAR(15) NULL,
    MaKhoa INT NOT NULL REFERENCES Khoa(MaKhoa)
);
GO