CREATE TABLE BenhNhan (
    MaBN INT PRIMARY KEY IDENTITY(1,1),
    HoTen NVARCHAR(100) NOT NULL,
    GioiTinh NVARCHAR(10) NULL,
    NgaySinh DATE NULL,
    DiaChi NVARCHAR(255) NULL,
    SDT NVARCHAR(15) NULL,
    MaBHYT NVARCHAR(20) NULL REFERENCES BaoHiemYTe(MaBHYT)
);
GO