CREATE TABLE ChiTietDichVu (
    MaCTDV INT PRIMARY KEY IDENTITY(1,1),
    MaHS INT NOT NULL REFERENCES HoSoKham(MaHS) ON DELETE CASCADE,
    MaDV INT NOT NULL REFERENCES DichVu(MaDV),
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    DonGia DECIMAL(18,2) NOT NULL CHECK (DonGia >= 0),
    ThanhTien AS (SoLuong * DonGia) PERSISTED,
    CONSTRAINT UQ_ChiTietDichVu_MaHS_MaDV UNIQUE (MaHS, MaDV)
);
GO