CREATE TABLE DonThuoc (
    MaDon INT PRIMARY KEY IDENTITY(1,1),
    MaHS INT NOT NULL REFERENCES HoSoKham(MaHS) ON DELETE CASCADE,
    MaBS INT NOT NULL REFERENCES BacSi(MaBS),
    TongTien DECIMAL(18,2) NULL,
    NgayKeDon DATE NOT NULL,
    GhiChu NVARCHAR(255) NULL
);
GO