CREATE TABLE HoaDon (
    MaHoaDon INT PRIMARY KEY IDENTITY(1,1),
    MaHS INT NOT NULL REFERENCES HoSoKham(MaHS),
    MaBN INT NOT NULL REFERENCES BenhNhan(MaBN),
    NgayLap DATETIME NOT NULL,
    TongTien DECIMAL(18,2) NOT NULL CHECK (TongTien >= 0),
    MaBHYT NVARCHAR(20) NULL REFERENCES BaoHiemYTe(MaBHYT),
    TyLeBHYT DECIMAL(5,2) NULL,
    TienBNPhaiTra DECIMAL(18,2) NULL
);
GO