CREATE TABLE HoSoKham (
    MaHS INT PRIMARY KEY IDENTITY(1,1),
    MaBN INT NOT NULL REFERENCES BenhNhan(MaBN),
    MaBS INT NOT NULL REFERENCES BacSi(MaBS),
    MaPhong INT NULL REFERENCES PhongKham(MaPhong),
    NgayKham DATETIME NOT NULL,
    MaBenh INT NULL REFERENCES Benh(MaBenh),
    TrieuChung NVARCHAR(255) NULL,
    ChanDoan NVARCHAR(255) NULL,
    GhiChu NVARCHAR(255) NULL
);
GO