INSERT INTO Benh (TenBenh, MoTa) VALUES
(N'Cảm cúm thông thường', N'Nhiễm virus đường hô hấp trên'),
(N'Viêm phổi cộng đồng', N'Viêm phổi do vi khuẩn hoặc virus'),
(N'Đái tháo đường type 2', N'Rối loạn chuyển hóa glucose'),
(N'Tăng huyết áp vô căn', N'Huyết áp cao không rõ nguyên nhân'),
(N'Viêm họng cấp', N'Viêm họng do streptococcus'),
(N'Sâu răng', N'Hư men răng do vi khuẩn'),
(N'Viêm da tiếp xúc', N'Phản ứng da với chất kích thích'),
(N'Đau nửa đầu migraine', N'Đau đầu mạch máu'),
(N'Loét dạ dày tá tràng', N'Loét niêm mạc dạ dày'),
(N'Rối loạn lipid máu', N'Tăng cholesterol hoặc triglyceride'),
(N'Viêm khớp dạng thấp', N'Bệnh tự miễn khớp'),
(N'Suy thận mạn', N'Suy giảm chức năng thận kéo dài'),
(N'Viêm gan B mạn', N'Nhiễm virus viêm gan B'),
(N'Ung thư phổi', N'Ung thư biểu mô phổi'),
(N'Viêm xoang cấp', N'Viêm xoang do nhiễm khuẩn'),
(N'Đục thủy tinh thể', N'Mờ đục thủy tinh thể mắt'),
(N'Gãy xương đùi', N'Gãy xương do chấn thương'),
(N'Viêm ruột thừa', N'Viêm cấp tính ruột thừa'),
(N'Nhiễm trùng đường tiết niệu', N'Nhiễm khuẩn bàng quang hoặc thận'),
(N'Rối loạn giấc ngủ', N'Mất ngủ hoặc ngủ nhiều'),
(N'Viêm đại tràng', N'Viêm niêm mạc đại tràng'),
(N'Bệnh Parkinson', N'Rối loạn vận động do thoái hóa thần kinh'),
(N'Viêm khớp gối', N'Viêm khớp do thoái hóa'),
(N'Hen suyễn', N'Co thắt phế quản dị ứng'),
(N'Bệnh Basedow', N'Cường giáp tự miễn'),
(N'Viêm amidan', N'Viêm amidan do vi khuẩn'),
(N'Loãng xương', N'Giảm mật độ xương'),
(N'Viêm bàng quang', N'Nhiễm trùng bàng quang'),
(N'U xơ tử cung', N'Khối u lành tính tử cung'),
(N'Viêm tuyến tiền liệt', N'Viêm tuyến tiền liệt nam giới'),
(N'Bệnh Alzheimer', N'Sa sút trí tuệ'),
(N'Viêm gan A', N'Nhiễm virus viêm gan A'),
(N'Sốt xuất huyết Dengue', N'Nhiễm virus Dengue'),
(N'Viêm màng não', N'Viêm màng não do vi khuẩn'),
(N'Bệnh lý van tim', N'Hẹp hoặc hở van tim'),
(N'Rối loạn nhịp tim', N'Loạn nhịp tim'),
(N'Viêm dạ dày', N'Viêm niêm mạc dạ dày'),
(N'Bệnh gout', N'Tăng acid uric máu'),
(N'Viêm tai giữa', N'Nhiễm trùng tai giữa'),
(N'Polyp mũi', N'Khối u lành tính mũi'),
(N'Viêm kết mạc', N'Viêm màng mắt'),
(N'Hội chứng ruột kích thích', N'Rối loạn chức năng ruột'),
(N'Bệnh Crohn', N'Viêm ruột mạn tính'),
(N'Viêm tụy cấp', N'Viêm tuyến tụy cấp tính'),
(N'Suy giáp', N'Giảm hormone tuyến giáp'),
(N'Ung thư vú', N'Ung thư biểu mô vú'),
(N'Ung thư đại tràng', N'Ung thư đại trực tràng'),
(N'Bệnh lý mạch vành', N'Xơ vữa động mạch vành'),
(N'Viêm phế quản mạn', N'Viêm phế quản kéo dài'),
(N'Suy tim sung huyết', N'Suy tim do ứ huyết');