INSERT INTO Khoa (TenKhoa, MoTa) VALUES
(N'Nội tổng hợp', N'Khám và điều trị các bệnh nội khoa tổng quát'),
(N'Ngoại tổng hợp', N'Phẫu thuật tổng quát và điều trị ngoại khoa'),
(N'Nhi khoa', N'Khám và điều trị bệnh cho trẻ em'),
(N'Tai Mũi Họng', N'Khám và điều trị các bệnh về tai mũi họng'),
(N'Răng Hàm Mặt', N'Khám và điều trị các bệnh răng miệng'),
(N'Da liễu', N'Điều trị các bệnh về da và phần phụ'),
(N'Tim mạch', N'Điều trị các bệnh về tim và mạch máu'),
(N'Hô hấp', N'Điều trị các bệnh về phổi và đường hô hấp'),
(N'Thần kinh', N'Khám và điều trị các bệnh thần kinh'),
(N'Sản phụ khoa', N'Chăm sóc sức khỏe sinh sản và thai sản'),
(N'Tiêu hóa', N'Điều trị các bệnh về đường tiêu hóa'),
(N'Thận - Tiết niệu', N'Điều trị bệnh thận và hệ tiết niệu'),
(N'Nội tiết', N'Điều trị rối loạn nội tiết và chuyển hóa'),
(N'Ung bướu', N'Điều trị ung thư và khối u'),
(N'Mắt', N'Khám và điều trị bệnh về mắt'),
(N'Chấn thương chỉnh hình', N'Điều trị chấn thương xương khớp'),
(N'Phục hồi chức năng', N'Phục hồi sau chấn thương hoặc phẫu thuật'),
(N'Truyền nhiễm', N'Điều trị các bệnh truyền nhiễm'),
(N'Dinh dưỡng', N'Tư vấn và điều trị rối loạn dinh dưỡng'),
(N'Tâm thần', N'Điều trị các bệnh tâm thần và tâm lý'),
(N'Huyết học', N'Điều trị bệnh về máu và cơ quan tạo máu'),
(N'Lao phổi', N'Điều trị bệnh lao và các bệnh phổi khác'),
(N'Vật lý trị liệu', N'Điều trị bằng phương pháp vật lý'),
(N'X quang', N'Chẩn đoán hình ảnh bằng X-quang'),
(N'Siêu âm', N'Chẩn đoán bằng siêu âm'),
(N'Nội soi', N'Chẩn đoán và điều trị nội soi'),
(N'Hồi sức cấp cứu', N'Chăm sóc bệnh nhân cấp cứu'),
(N'Gây mê hồi sức', N'Quản lý gây mê và hồi sức'),
(N'Dược lâm sàng', N'Tư vấn sử dụng thuốc'),
(N'Kiểm soát nhiễm khuẩn', N'Ngăn ngừa nhiễm khuẩn bệnh viện'),
(N'Y học cổ truyền', N'Điều trị bằng y học cổ truyền'),
(N'Châm cứu', N'Điều trị bằng châm cứu'),
(N'Dị ứng miễn dịch', N'Điều trị dị ứng và rối loạn miễn dịch'),
(N'Lão khoa', N'Chăm sóc sức khỏe người cao tuổi'),
(N'Nhi sơ sinh', N'Chăm sóc trẻ sơ sinh'),
(N'Thẩm mỹ', N'Phẫu thuật thẩm mỹ'),
(N'Bỏng', N'Điều trị bỏng'),