INSERT INTO PhongKham (TenPhong, MaKhoa, ViTri) VALUES
(N'Phòng khám n?i 1', 1, N'T?ng 1, Khu A'),
(N'Phòng khám ngo?i 1', 2, N'T?ng 2, Khu B'),
(N'Phòng khám nhi 1', 3, N'T?ng 3, Khu C'),
(N'Phòng khám TMH 1', 4, N'T?ng 1, Khu D'),
(N'Phòng khám RHM 1', 5, N'T?ng 2, Khu E'),
(N'Phòng khám da li?u 1', 6, N'T?ng 3, Khu F'),
(N'Phòng khám tim m?ch 1', 7, N'T?ng 1, Khu G'),
(N'Phòng khám hô h?p 1', 8, N'T?ng 2, Khu H'),
(N'Phòng khám th?n kinh 1', 9, N'T?ng 3, Khu I'),
(N'Phòng khám s?n 1', 10, N'T?ng 1, Khu J'),
(N'Phòng khám tiêu hóa 1', 11, N'T?ng 2, Khu K'),
(N'Phòng khám th?n 1', 12, N'T?ng 3, Khu L'),
(N'Phòng khám n?i ti?t 1', 13, N'T?ng 1, Khu M'),
(N'Phòng khám ung b??u 1', 14, N'T?ng 2, Khu N'),
(N'Phòng khám m?t 1', 15, N'T?ng 3, Khu O'),
(N'Phòng khám ch?nh hình 1', 16, N'T?ng 1, Khu P'),
(N'Phòng khám ph?c h?i 1', 17, N'T?ng 2, Khu Q'),
(N'Phòng khám truy?n nhi?m 1', 18, N'T?ng 3, Khu R'),
(N'Phòng khám dinh d??ng 1', 19, N'T?ng 1, Khu S'),
(N'Phòng khám tâm th?n 1', 20, N'T?ng 2, Khu T'),
(N'Phòng khám huy?t h?c 1', 21, N'T?ng 3, Khu U'),
(N'Phòng khám lao 1', 22, N'T?ng 1, Khu V'),
(N'Phòng v?t lý tr? li?u 1', 23, N'T?ng 2, Khu W'),
(N'Phòng X quang 1', 24, N'T?ng 3, Khu X'),
(N'Phòng siêu âm 1', 25, N'T?ng 1, Khu Y'),
(N'Phòng n?i soi 1', 26, N'T?ng 2, Khu Z'),
(N'Phòng c?p c?u 1', 27, N'T?ng 3, Khu AA'),
(N'Phòng gây mê 1', 28, N'T?ng 1, Khu AB'),
(N'Phòng d??c 1', 29, N'T?ng 2, Khu AC'),
(N'Phòng nhi?m khu?n 1', 30, N'T?ng 3, Khu AD'),
(N'Phòng y h?c c? truy?n 1', 31, N'T?ng 1, Khu AE'),
(N'Phòng châm c?u 1', 32, N'T?ng 2, Khu AF'),
(N'Phòng d? ?ng 1', 33, N'T?ng 3, Khu AG'),
(N'Phòng lão khoa 1', 34, N'T?ng 1, Khu AH'),
(N'Phòng nhi s? sinh 1', 35, N'T?ng 2, Khu AI'),
(N'Phòng th?m m? 1', 36, N'T?ng 3, Khu AJ'),
(N'Phòng b?ng 1', 37, N'T?ng 1, Khu AK'),
(N'Phòng ghép t?ng 1', 38, N'T?ng 2, Khu AL'),
(N'Phòng hô h?p nhi 1', 39, N'T?ng 3, Khu AM'),
(N'Phòng tim m?ch nhi 1', 40, N'T?ng 1, Khu AN'),
(N'Phòng th?n kinh nhi 1', 41, N'T?ng 2, Khu AO'),
(N'Phòng tiêu hóa nhi 1', 42, N'T?ng 3, Khu AP'),
(N'Phòng ung th? nhi 1', 43, N'T?ng 1, Khu AQ'),
(N'Phòng da li?u nhi 1', 44, N'T?ng 2, Khu AR'),
(N'Phòng n?i ti?t nhi 1', 45, N'T?ng 3, Khu AS'),
(N'Phòng th?n nhi 1', 46, N'T?ng 1, Khu AT'),
(N'Phòng m?t nhi 1', 47, N'T?ng 2, Khu AU'),
(N'Phòng TMH nhi 1', 48, N'T?ng 3, Khu AV'),
(N'Phòng RHM nhi 1', 49, N'T?ng 1, Khu AW'),
(N'Phòng ch?n th??ng nhi 1', 50, N'T?ng 2, Khu AX');
